__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

__Решение__

$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0,$

$(-1-\lambda)(6-\lambda)-2\cdot (-6)=0,$

$\lambda^{2}-5 \lambda + 6=0,$

$\lambda=2,3$ -  собственные значения.

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix} \begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix} = 2 \begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}$

$\begin{cases}
-x_1 - 6x_2 = 2x_1 \\ 
2x_1+6x_2=2x_2
\end{cases}
\Leftrightarrow
\begin{cases}
x_1+2x_2 = 0\\ 
0=0
\end{cases}
\Rightarrow
\begin{pmatrix}
2\\ 
-1
\end{pmatrix}$ - собственный вектор $A$ с собственным значением $\lambda = 2$.

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix} \begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix} = 3 \begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}$

$\begin{cases}
-x_1 - 6x_2 = 3x_1 \\ 
2x_1+6x_2=3x_2
\end{cases}
\Leftrightarrow
\begin{cases}
2x_1+3x_2 = 0\\ 
0=0
\end{cases}
\Rightarrow
\begin{pmatrix}
3\\ 
-2
\end{pmatrix}$ - собственный вектор $A$ с собственным значением $\lambda = 3$.

In [2]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [6]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v[:, 0]/(-v[1, 0])}\n{v[:, 1]*2/(-v[1, 1])}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[ 2. -1.]
[ 3. -2.]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

__Решение__

$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}=
\begin{pmatrix}
-x_1\\ 
-x_2
\end{pmatrix}=(-1) \cdot
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}$

По определению это означает, что любой вектор является собственным и его собственное значение равно -1.

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

__Решение__

$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix}=
\begin{pmatrix}
2\\ 
2
\end{pmatrix}= 2 \cdot
\begin{pmatrix}
1\\ 
1
\end{pmatrix}$

По определению это означает, что вектор $x=(1,1)$ является собственным и его собственное значение равно 2.

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

__Решение__

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}=
\begin{pmatrix}
-9\\ 
9\\
-12
\end{pmatrix}=(-3) \cdot
\begin{pmatrix}
3\\ 
-3\\
4
\end{pmatrix} \neq \lambda
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}, \forall \lambda$

Следовательно вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора $A$.

Найдем собственные векторы и собственные значения оператора $A$.

$\begin{vmatrix}
0-\lambda & 3 & 0\\ 
3 & 0-\lambda & 0\\
0 & 0 & 3-\lambda
\end{vmatrix}=\lambda^2(3-\lambda)-9(3-\lambda)=0 \Rightarrow \lambda = \pm 3$ - собственные значения (корень 3 кратности 2).

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
x_1\\ 
x_2\\
x_3
\end{pmatrix}=
\begin{pmatrix}
3x_2\\ 
3x_1\\
3x_3
\end{pmatrix}=3 \cdot
\begin{pmatrix}
x_1\\ 
x_2\\
x_3
\end{pmatrix} \Rightarrow
\begin{cases}
x_2=x_1\\
x_1=x_2\\
x_3=x_3
\end{cases} \Rightarrow $ вектор $(1,1,1)$ - собственный с собственным значением 3.

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
x_1\\ 
x_2\\
x_3
\end{pmatrix}=
\begin{pmatrix}
3x_2\\ 
3x_1\\
3x_3
\end{pmatrix}=(-3) \cdot
\begin{pmatrix}
x_1\\ 
x_2\\
x_3
\end{pmatrix} \Rightarrow
\begin{cases}
x_2=-x_1\\
x_1=-x_2\\
x_3=-x_3
\end{cases} \Rightarrow $ вектор $(1,-1,0)$ - собственный с собственным значением -3.

In [9]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v[:, 0]/v[0, 0]+v[:, 2]}\n{v[:, 1]/(-v[1, 1])}')
### так как первое и третье собственные значения совпадают, 
### то первый и третий собственные вектора можем сложить и получить собственный вектор с тем же собственным значением

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[1. 1. 1.]
[ 1. -1. -0.]
