### Часть 1

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__Решение__

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix} \rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix} \rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & 1 & -1 & -5\\ 
0 & 0 & 1 & -\frac 32
\end{matrix}\right|
\begin{matrix}
0\\ 
2\\
-2
\end{matrix}
\end{pmatrix} \Rightarrow
\begin{cases}
x_4=2c\\
x_3=-2+3c\\
x_2=2+10c+3c-2=13c\\
x_1=4c-2+3c-13c=-6c-2
\end{cases}$.

Ответ: $(-6c-2,13c,-2+3c,2c), \forall c$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

__Решение__

а) Число уравнений равно числу неизвестных и матрица невырождена ($det A = -32 \neq 0$), следовательно существует единсвтенное решение

б) векторы коэффициентов принадлежат одномерному пространству (пропорциональны друг другу), а вектор b не принадлежит этому подпростанству, поэтому систему несовместна

в) $rank A = 2$ и $rank \tilde A = 2$, следовательно по теореме Кронекера-Капелли система совместна и имеет бесконечно много решений (ранг проставнства решений равен 3-2=1)

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

__Решение__

Матрица A квартратная и $det A = 30 \neq 0$, следовательно решение существует и единственно.

Второй вариант решения: $rankA=rank \tilde A=4$, и $4$ — число неизвестных, следовательно система имеет единственное решение.

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix} \rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
-4a+b\\
-7a+c
\end{matrix}
\end{pmatrix} \rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
-4a+b\\
a-2b+c
\end{matrix}
\end{pmatrix},$ 

следовательно, если $a-2b+c \neq 0$, то система несовместна.

### Часть 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

__Решение__

а) $A=\begin{pmatrix}
1 & -2 \\
3 & -4
\end{pmatrix}, 
b = \begin{pmatrix}
1 \\
7
\end{pmatrix}$

$det A = -4 + 6 = 2$

$det A_1 = \begin{vmatrix}
1 & -2 \\
7 & -4
\end{vmatrix} = -4+14=10$

$det A_2 = \begin{vmatrix}
1 & 1 \\
3 & 7
\end{vmatrix} = 7-3=4$

$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5,$

$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2$

а) $A=\begin{pmatrix}
2 & -1 & 5 \\
1 & 1 & -3 \\
2 & 4 & 1
\end{pmatrix}, 
b = \begin{pmatrix}
10 \\
-2 \\
1
\end{pmatrix}$

$det A =  2 + 6 + 20 - 10 + 24 + 1 = 43$

$det A_1 = \begin{vmatrix}
10 & -1 & 5 \\
-2 & 1 & -3 \\
1 & 4 & 1
\end{vmatrix} =10+3-40-5+120-2=86$

$det A_2 = \begin{vmatrix}
2 & 10 & 5 \\
1 & -2 & -3 \\
2 & 1 & 1
\end{vmatrix} = -4-60+5+20+6-10=-43$

$det A_2 = \begin{vmatrix}
2 & -1 & 10 \\
1 & 1 & -2 \\
2 & 4 & 1
\end{vmatrix} = 2+4+40-20+16+1=43$

$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2$

$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1$

$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1$

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

__Решение__

а)
Преобразование A 
$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix} \rightarrow 
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}\rightarrow 
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$

Соотвующ. заполнение L
$\begin{pmatrix}
1 & 0 & 0 \\ 
* & 1 & 0 \\ 
* & * & 1
\end{pmatrix} \rightarrow 
\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & * & 1
\end{pmatrix}\rightarrow 
\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$

$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}, U = \begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$

б)
Преобразование A 
$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix} \rightarrow 
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}\rightarrow 
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}\rightarrow 
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$

Соотвующ. заполнение L
$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
* & 1 & 0 & 0 \\ 
* & * & 1 & 0 \\ 
* & * & * & 1
\end{pmatrix} \rightarrow 
\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & * & 1 & 0 \\ 
4 & * & * & 1
\end{pmatrix}\rightarrow 
\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\ 
4 & 6 & * & 1
\end{pmatrix} \rightarrow 
\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\ 
4 & 6 & 7 & 1
\end{pmatrix}$

$L=\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\ 
4 & 6 & 7 & 1
\end{pmatrix} U = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__Решение__

Преобразование A 
$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix} \rightarrow 
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac 32 & -\frac{23}{2} \\ 
0 & \frac 72 & -\frac{19}{2}
\end{pmatrix}\rightarrow 
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac 32 & -\frac{23}{2} \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}$

Соотвующ. заполнение L
$\begin{pmatrix}
1 & 0 & 0 \\ 
* & 1 & 0 \\ 
* & * & 1
\end{pmatrix} \rightarrow 
\begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & * & 1
\end{pmatrix}\rightarrow 
\begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & \frac{7}{3} & 1
\end{pmatrix}$

$L=\begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & \frac{7}{3} & 1
\end{pmatrix}, U = \begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac 32 & -\frac{23}{2} \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}$

$Ly=b: 
\begin{cases}
y_1 = &1 \\
\frac{11}{2}y_1 + y_2 = &-6\\
\frac{9}{2}y_1 + \frac{7}{3}y_2 + y_3 = &-5
\end{cases} \Leftrightarrow
\begin{cases}
y_1 = 1 \\
y_2 = -\frac{23}{2}\\
y_3 = \frac{52}{3}
\end{cases}$

$Ux=y: 
\begin{cases}
2x_1&+x_2&+3x_3 = &1 \\
&\frac{3}{2}x_2 &- \frac{23}{2} x_3 = &-\frac{23}{2}\\
&&\frac{52}{3}x_3 = &\frac{52}{3}
\end{cases} \Leftrightarrow
\begin{cases}
x_1 = -1 \\
x_2 = 0\\
x_3 = 1
\end{cases}$

Ответ: $(-1, 0, 1)$.

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

__Решение__

$l_{11}=\sqrt{a_{11}}=\sqrt{81} = 9,$

$l_{21}=\frac{a_{21}}{l_{11}}=-\frac{45}{9} = -5,$

$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$

$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50-25}=5,$

$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac 15 (-15 - (-5)5) = 2,$

$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=3.$

$L=\begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3 
\end{pmatrix}, L^T = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3 
\end{pmatrix}$

$Ly=b: 
\begin{cases}
9y_1 = &531 \\
-5y_1 + 5y_2 = &-460\\
5y_1 + 2y_2 + 3y_3 = &193
\end{cases} \Leftrightarrow
\begin{cases}
y_1 = 59 \\
y_2 = -33\\
y3 = -12
\end{cases}$

$Ux=y: 
\begin{cases}
9x_1&-5x_2&+5x_3 = &59 \\
&5x_2 &+2x_3 = &-33\\
&&3x_3 = &-12
\end{cases} \Leftrightarrow
\begin{cases}
x_1 = 6 \\
x_2 = -5\\
x_3 = -4
\end{cases}$

Ответ: $(6, -5, -4)$.

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [42]:
import numpy as np

In [43]:
def kramer_method (a, b):
    x = list()
    n, m = a.shape
    if n!=m:
        print('Матрица не квадратная, решение методом Крамера невозможно')
        return
    det_a = np.linalg.det(a)
    if det_a == 0:
        print('Определитель равен нулю, система вырождена')
        return
    for i in range(n):
        c = a.copy()
        c[:, i] = b
        x.append(np.linalg.det(c)/det_a)
    return np.array(x)

In [44]:
a = np.array([[1,-2],[3,-4]])
b=np.array([1,7])
print(f'Матрица A:\n{a}')
print(f'Свободный член b:\n{b}')
print(f'Решение x:\n{kramer_method(a,b)}')

Матрица A:
[[ 1 -2]
 [ 3 -4]]
Свободный член b:
[1 7]
Решение x:
[5. 2.]


In [45]:
a = np.array([[2,-1,5],[1,1,-3],[2,4,1]])
b=np.array([10,-2,1])
print(f'Матрица A:\n{a}')
print(f'Свободный член b:\n{b}')
print(f'Решение x:\n{kramer_method(a,b)}')

Матрица A:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
Свободный член b:
[10 -2  1]
Решение x:
[ 2. -1.  1.]
