### Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

__Решение__

а) нет, так как $2 \neq 4$

б) да, $2 \times 3$

в) да, $8 \times 8$

г) да, $4 \times 4$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__Решение__

$A+B=\begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0+5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

$A \cdot B=\begin{pmatrix}
1 \cdot 4-2 \cdot 0 & 1 \cdot (-1)-2 \cdot 5\\ 
3 \cdot 4 + 0 \cdot 0 & 3 \cdot (-1)+0 \cdot 5
\end{pmatrix} = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [3]:
import numpy as np

In [5]:
A = np.array([[1,-2],[3,0]])
B = np.array([[4,-1],[0,5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица A+B\n{A+B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица A+B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

__Решение__

$3 \cdot \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2 \cdot \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4 \cdot \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3 \cdot 1 -2 \cdot 0 + 4 \cdot 2 & 3 \cdot 7 -2 \cdot 5 + 4 \cdot (-4)\\ 
3 \cdot 3 -2 \cdot 2 + 4 \cdot 1 & 3 \cdot (-6) -2 \cdot (-1) + 4 \cdot 1
\end{pmatrix} = 
\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [9]:
A = np.array([[1,7], [3,-6]])
B = np.array([[0,5], [2,-1]])
C = np.array([[2,-4], [1,1]])

3*A-2*B+4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$AA^{T}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$

$A^{T}A=\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

In [11]:
A = np.array([[4,1],[5,-2],[2,3]])

print(np.dot(A, A.T))
print(np.dot(A.T, A))

[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [42]:
def matrix_product (A, B):
    m1 = np.shape(A)[0]
    n1 = np.shape(A)[1]
    m2 = np.shape(B)[0]
    n2 = np.shape(B)[1]
    
    if n1 != m2:
        print('Умножение невозможно: {n1} не равно {m2}')
        return
    
    c_matr = list()
    for i in range(m1):
        c_str = list()
        for j in range(n2):
            c = 0
            for k in range(n1):
                c += A[i][k]*B[k][j]
            c_str.append(c)
        c_matr.append(c_str)
        
    return np.array(c_matr)

In [44]:
A = np.array([[4,1],[5,-2],[2,3]])

print(matrix_product(A, A.T))
print(matrix_product(A.T, A))

[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


### Часть 2

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


а) $det A = \sin^2 x + \cos ^2 x = 1$

б) $det A = 4 \cdot 5 \cdot 9 = 180$

в) $\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} =  \begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{vmatrix} = 0$, так как матрица содержит линейно зависимые строки

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

__Решение__

а) $det(A^{2}) = (det A)^{2} = 16$;
    
б) $det(A^{T}) = det A = 4$;
    
в) $det(2A) = 2^n det A = 2^n \cdot 4 = 2^{n+2}$, где n - размерность матрицы A

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__Док-во__

Строки 1 и 2 матрицы линейно зависимы (строка 1 * 2 + строка 2 = 0), следовательно определитель равен нулю, то есть матрица вырожденная

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

   а) $rk\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix} = rk\begin{pmatrix}
0 & 1 & 2\\ 
1 & 1 & 1\\ 
0 & 1 & 2
\end{pmatrix} = 
rk\begin{pmatrix}
0 & 0 & 0\\ 
1 & 1 & 1\\ 
0 & 1 & 2
\end{pmatrix} = 2$

б) $rk\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}=3$, так как 
$\begin{vmatrix}
 0 & 2 & 2\\ 
 0 & 4 & 3\\ 
 3 & 5 & 6
\end{vmatrix} \neq 0$ - базисный минор